### ISSUE TITLE
Fatal error: Class 'BP_Blogs_Blog'

### ISSUE THREAD

**Issue by danaskallman** [christianwach/bp-group-sites#1]
I was testing/looking at the functions of this plugin and when I am on a Groups Manage page and go to the Groups Sites settings I get the following:

`Fatal error: Class 'BP_Blogs_Blog' not found in .../plugins/bp-group-sites/includes/bpgsites-linkage.php on line 519`

On the Groups main menu Groups Sites menu for all visitors to view I get the following fatal error:

`Fatal error: Call to undefined function bp_has_blogs() in .../plugins/bp-group-sites/includes/bpgsites-blogs.php on line 88` 

Thoughts on why? Is there something I'm missing in terms of setup needs?

**Comment by christianwach** [comment]
@danaskallman Is the BuddyPress "Site Tracking" component active in "Network Admin -> Settings -> BuddyPress"?

**Comment by danaskallman** [comment]
@christianwach aha, that was missing piece. Thanks!
